repos:
  - repo: https://github.com/myint/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        exclude: .*/__init__.py
        args:
          - --in-place
          - --remove-all-unused-imports
          - --expand-star-imports
          - --remove-duplicate-keys
          - --remove-unused-variables

  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: "6.1.0" # pick a git hash / tag to point to
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.6.1"
    hooks:
      - id: mypy
        args:
          - "--follow-imports=silent"
          - "--ignore-missing-imports"
          - "--show-column-numbers"

        additional_dependencies:
          - "pydantic>=2,<3"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
